import org.apache.commons.io.IOUtils

plugins {
    id 'java'
    id 'maven-publish'
    id "idea"
    id "maven-publish"
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id "com.matthewprenger.cursegradle" version "1.4.0"
    id 'org.spongepowered.mixin' version '0.7.+'
    id "com.modrinth.minotaur" version "2.+"
}

apply plugin: 'org.spongepowered.mixin'
apply plugin: "java"
jarJar.enable()

allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile).tap {
            configureEach {
                options.compilerArgs << "-Xmaxerrs" << "1000" << "-h" << ("${layout.buildDirectory.get().toString().replace("\\", "/")}/c" as String)
            }
        }
    }
}

def getGitRef() {
    try {
        final def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    } catch (final Throwable ignored) {
        return 'unknown'
    }
}

version = "${semver}+${getGitRef()}"
group = 'com.therealm18.minux'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    mavenCentral()
}


final def hasGithubPackageCredentials =
    (project.hasProperty("gpr.user") && project.hasProperty("gpr.key")) ||
        (System.getenv("GITHUB_ACTOR") && System.getenv("GITHUB_TOKEN"))

repositories {
    mavenCentral()
    maven {
        url "https://cursemaven.com"
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"

    implementation fileTree(dir: 'libs', include: '*.jar')
//    implementation "curse.maven:sedna-511276:3885542"
    minecraftLibrary "org.apache.commons:commons-collections4:${apache_commons_version}"

    implementation fg.deobf("curse.maven:architectury-api-${architectury_project_id}:${architectury_file_id}")
    implementation fg.deobf("curse.maven:markdownmanual-${markdownmanual_project_id}:${markdownmanual_file_id}")
    implementation fg.deobf("curse.maven:oc2r-1037738:6899236")
    
    // Test Dependencies
    testImplementation "org.mockito:mockito-inline:${mockito_version}"
    testImplementation "org.junit.jupiter:junit-jupiter-api:${jupiter_version}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${jupiter_version}"
}

System.setProperty("line.separator", "\n")

tasks.register('packageScripts', Zip) {
    archiveFileName = "scripts.zip"
    destinationDirectory = file("${layout.buildDirectory.get()}/resources/main/data/minux/file_systems")
    from "src/main/scripts"
    filter { line -> line }
}

tasks.register('copyLicensesToResources', Copy) {
    from "."
    into file("${layout.buildDirectory.get()}/resources/main")
    include "LICENSE*"
}

processResources.dependsOn(packageScripts)
processResources.dependsOn(copyLicensesToResources)

tasks.named('jarJar'){
}

minecraft {
    mappings channel: "official", version: minecraft_version

    runs {
        configureEach {
            property "forge.logging.markers", "REGISTRIES"
            property "forge.logging.console.level", "debug"

            mods {
                oc2 {
                    source sourceSets.main
                }
            }
        }

        client {
            workingDirectory project.file("runclient")
            property "forge.enabledGameTestNamespaces", "minux"
        }

        server {
            workingDirectory project.file("run")
            property "forge.enabledGameTestNamespaces", "minux"
            arg "--nogui"
        }

        gameTestServer {
            workingDirectory project.file('run')
            property "forge.enabledGameTestNamespaces", "minux"
        }

        data {
            workingDirectory project.file("run")
            args "--mod", "minux", "--all", "--output", file("src/generated/resources/"), "--existing", file("src/main/resources")
        }
    }
}

tasks.register('copyGeneratedResources', Copy) {
    from "src/generated"
    into "src/main"
    exclude "resources/.cache"
}

jar {
    finalizedBy "reobfJar"

    manifest {
        attributes([
            "FMLAT"                   : "accesstransformer.cfg",
            "Specification-Title"     : "minux",
            "Specification-Vendor"    : "TheRealM18",
            "Specification-Version"   : "1",
            "Implementation-Title"    : project.name,
            "Implementation-Version"  : "${semver}",
            "Implementation-Vendor"   : "TheRealM18",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
        ])
    }
}

publish {
    dependsOn(tasks.modrinth)
    dependsOn(tasks.curseforge)
}

artifacts {
    archives apiJar
}

static def getCurseforgeSDKValue(minecraft_sdk) {
    switch(minecraft_sdk) {
        case "forge": return "Forge"
        case "fabric": return "Fabric"
        case "neoforge": return "NeoForge"
        case "quilt": return "Quilt"
        default: throw new Exception("Unrecognized minecraft SDK")
    }
}

curseforge {
    apiKey = System.getenv("CURSEFORGE_API_KEY") ?: ""

    project {
        id = curse_project_id
        releaseType = System.getenv('RELEASE_TYPE') ?: "alpha"
        changelogType = 'markdown'
        changelog = System.getenv("CHANGELOG") ?: "Changelog not available."
        addGameVersion getCurseforgeSDKValue(minecraft_sdk)
        addGameVersion minecraft_version
        addGameVersion "Java 17"
        mainArtifact "build/libs/minux-${minecraft_version}-${minecraft_sdk}-${version}.jar"
        relations {
            requiredDependency "markdownmanual",
            requiredDependency "oc2r"
        }
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = modrinth_project_id
    versionType = System.getenv('RELEASE_TYPE') ?: "alpha"
    uploadFile = "build/libs/minux-${minecraft_version}-${minecraft_sdk}-${version}.jar"
    gameVersions = [minecraft_version]
    loaders = [minecraft_sdk]
    changelog = System.getenv("CHANGELOG") ?: "Changelog not available."
    dependencies {
        required.project "markdownmanual",
        required.project "oc2r"
    }
}

idea {
    module {
        for (final String exclude in ["assets", "run", "out", "logs", "src/generated"]) {
            excludeDirs += file(exclude)
        }
    }
}

test {
    useJUnitPlatform()
}

compileJava {
    options.encoding = "UTF-8"
}

import org.apache.tools.ant.taskdefs.condition.Os

task cleanBuildroot(type: Exec) {
    if (Os.isFamily(Os.FAMILY_UNIX)) {
        commandLine("make", "clean")
    }
}
clean.dependsOn cleanBuildroot

task compileBuildroot(type: Exec) {
    if (Os.isFamily(Os.FAMILY_UNIX)) {
        commandLine("make")
        commandLine("sed -i 's|minux|minux|g' sedna-mc/build.gradle")
        commandLine("minux-bootfs/build.sh")
    } else {
        logger.log(LogLevel.WARN, "Can only make buildroot on Linux. Expecting output files to have been manually placed in [output/images/] and [minux-bootfs/].")
        enabled = false
    }
    outputs.files "output/images/fw_jump.bin", "output/images/Image", "output/images/rootfs.cramfs", "minux-bootfs/bootfs.squashfs"
    outputs.upToDateWhen { false }
}

task generateLegalInfo(type: Exec) {
    if (Os.isFamily(Os.FAMILY_UNIX)) {
        commandLine("make", "legal-info")
    } else {
        enabled = false
    }
    outputs.dirs "output/legal-info/licenses"
    outputs.upToDateWhen { false }
}

task copyBuildrootImages(type: Copy) {
    from compileBuildroot.outputs.files
    into "src/main/resources/generated/"
}

task copyBuildrootLicenses(type: Copy) {
    from generateLegalInfo.outputs.files
    into "src/main/resources/licenses/"
}

copyBuildrootImages.dependsOn(compileBuildroot)
copyBuildrootImages.dependsOn(generateLegalInfo)
compileJava.dependsOn(copyBuildrootImages)
compileJava.dependsOn(copyBuildrootLicenses)

processResources.dependsOn(copyBuildrootImages)
processResources.dependsOn(copyBuildrootLicenses)

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = project.group
            artifactId = project.name
            version = semver
            artifact jar
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = System.getenv("GITHUB_MAVEN_URL") ?: ""
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
