name: build

on:
  workflow_dispatch:
  push:
    branches: [ 'x11' ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: build
        run: |
          git clone https://github.com/TheRealM18/damos.git -b '${{ github.ref_name }}'
          wget https://github.com/North-Western-Development/minux/releases/download/0.0.47/cache.tar.zst
          tar -C ~ -xf cache.tar.zst
          mv ~/dl minux
          rm cache.tar.zst
          git clone https://github.com/North-Western-Development/sedna-mc.git
          cd sedna-mc
          ./gradlew -Psemver=99.99.99 build

        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@v4
        with:
          name: damos.jar
          path: damos-mc/build/libs/*.jar
