name: build

on:
  workflow_dispatch:
  push:
    branches: [ 'x11' ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: build
        run: |
          git clone https://github.com/therealm18/damos.git -b '${{ github.ref_name }}'
          ./gradlew -Psemver=99.99.99 build

        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@v4
        with:
          name: damos.jar
          path: damos-mc/build/libs/*.jar
